### ISSUE TITLE
Will "wait" return on events that have already happened?

### ISSUE THREAD

**Issue by JosuGZ** [smol-rs/polling#168]
Let's say we have the following flow:

```
Time:  0.000 - Sleep 10 seconds
Time:  4.000 - A read event happens
Time: 10.000 - Sleep ends
Time: 10.001 - We call "modify" an express interest on the event
Time: 10.002 - We call "wait"
```

Currently I get the read event, but I'm not sure if this is guaranteed to happen (I think it should, since even without sleeping, events could happen just before the "modify").

Perhaps this could be clarified in the documentation.

**Comment by notgull** [comment]
Depends on the mode registered:

- For `Oneshot` (default) and `Level` triggered modes, the event would be delivered. For any of these modes, they emit events if the source is ready, no matter when the readiness started.
- `Edge` triggered is more complicated. Here it only happens if the event happens during the wait.
