### ISSUE TITLE
[question] Can we use polling integrate with web app? Thank you.

### ISSUE THREAD

**Issue by selfhostrepo** [smol-rs/polling#61]
if yest, where can we get started doing so?

**Comment by zeenix** [comment]
> if yest, where can we get started doing so?

Not sure what you mean exactly. Could you please elaborate a bit? Is there any specific web app or framework you are trying to integrate with? Have you run into any problems trying to do so?

**Comment by notgull** [comment]
If you're asking if you can use `polling` on a backend server: yes, you can! Although, I'd recommend using [`async-io`](https://crates.io/crates/async-io) or [`async-net`](https://crates.io/crates/async-net) instead of this crate directly, since they provide more idiomatic interfaces over this crate's functionality. If you're using [`hyper`](https://crates.io/crates/hyper), you need to write your own [`Accept`](https://docs.rs/hyper/latest/hyper/server/accept/trait.Accept.html) implementation. See [this example](https://github.com/smol-rs/smol/blob/master/examples/hyper-server.rs) to see how this could be done.

However, `polling` cannot be used on the frontend, since raw WASM does not support any realistic polling mechanisms.
