### ISSUE TITLE
NetBSD fails precision tests

### ISSUE THREAD

**Issue by notgull** [smol-rs/polling#75]
When running tests on NetBSD 9.3, they fail with the following:

```
     Running tests/precision.rs (target/debug/deps/precision-f95066041a1e286b)

running 2 tests
test above_ms ... FAILED
test below_ms ... FAILED

failures:

---- above_ms stdout ----
thread 'above_ms' panicked at 'assertion failed: lowest < dur + margin', tests/precision.rs:81:9

---- below_ms stdout ----
thread 'below_ms' panicked at 'assertion failed: lowest < dur + margin', tests/precision.rs:40:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    above_ms
    below_ms
```

I'm not sure if this also affects OpenBSD. This does not affect FreeBSD or MacOS.

**Comment by taiki-e** [comment]
I tested FreeBSD, NetBSD, OpenBSD, and Dragonfly BSD with [vmactions](https://github.com/vmactions), and precision tests failed in both debug and release modes for NetBSD, OpenBSD, and Dragonfly BSD (log: [release](https://github.com/smol-rs/polling/actions/runs/3979908967), [debug](https://github.com/smol-rs/polling/actions/runs/3979909569)).

It is possible that it is due to VM is slow, but given that those tests passed on FreeBSD VM, where the CI time is not that different, and the tests [failed even after increasing `margin` by 10 times](https://github.com/smol-rs/polling/actions/runs/3980043519), probably should be considered platform issues for now.
